import 'package:flutter/material.dart';import 'package:coffee_app/core/app_export.dart';import 'package:coffee_app/widgets/app_bar/appbar_leading_image.dart';import 'package:coffee_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:coffee_app/widgets/app_bar/custom_app_bar.dart';import 'package:coffee_app/widgets/custom_elevated_button.dart';import 'package:coffee_app/widgets/custom_icon_button.dart';import 'controller/tracking_orders_controller.dart';class TrackingOrdersScreen extends GetWidget<TrackingOrdersController> {const TrackingOrdersScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(height: 818.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgScreenshot20221008, height: 823.v, width: 428.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.fromLTRB(23.h, 30.v, 23.h, 34.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 395.v, width: 109.h, margin: EdgeInsets.only(left: 119.h), child: Stack(alignment: Alignment.topRight, children: [Align(alignment: Alignment.topLeft, child: Container(height: 30.adaptSize, width: 30.adaptSize, margin: EdgeInsets.only(left: 16.h), decoration: BoxDecoration(color: appTheme.black900.withOpacity(0.25), borderRadius: BorderRadius.circular(15.h)))), CustomImageView(imagePath: ImageConstant.imgVector13, height: 276.v, width: 88.h, alignment: Alignment.topRight, margin: EdgeInsets.only(top: 22.v)), Align(alignment: Alignment.topLeft, child: Container(height: 18.adaptSize, width: 18.adaptSize, margin: EdgeInsets.only(left: 22.h, top: 6.v), decoration: BoxDecoration(color: theme.colorScheme.onPrimary.withOpacity(1), borderRadius: BorderRadius.circular(9.h), border: Border.all(color: theme.colorScheme.primary, width: 5.h)))), CustomImageView(imagePath: ImageConstant.imgSettingsBlack900, height: 94.v, width: 50.h, alignment: Alignment.bottomLeft, margin: EdgeInsets.only(left: 13.h)), Padding(padding: EdgeInsets.only(bottom: 76.v), child: CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(8.h), decoration: IconButtonStyleHelper.outlineBlackTL20, alignment: Alignment.bottomLeft, child: CustomImageView(imagePath: ImageConstant.imgImage53))), CustomImageView(imagePath: ImageConstant.imgImage40, height: 43.adaptSize, width: 43.adaptSize, alignment: Alignment.bottomRight, margin: EdgeInsets.only(right: 22.h, bottom: 12.v))])), Spacer(), _buildMrSakira(), SizedBox(height: 10.v), CustomElevatedButton(height: 58.v, text: "msg_delivery_15_minutes".tr, buttonStyle: CustomButtonStyles.fillAmberATL20, buttonTextStyle: CustomTextStyles.headlineSmallBlack900_2)])))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 51.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 67.v, bottom: 19.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_track_order".tr, margin: EdgeInsets.only(top: 58.v, bottom: 11.v)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildMrSakira() { return Container(padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 13.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgEllipse46, height: 80.adaptSize, width: 80.adaptSize, radius: BorderRadius.circular(40.h), margin: EdgeInsets.only(top: 6.v, bottom: 9.v)), Padding(padding: EdgeInsets.only(left: 10.h, top: 6.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_mr_sakira".tr, style: CustomTextStyles.headlineSmallBlack900Medium), Text("lbl_food_deliver".tr, style: CustomTextStyles.bodyLargeBlack900_3), SizedBox(height: 2.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgSignal, height: 14.v, width: 15.h, margin: EdgeInsets.only(top: 2.v, bottom: 7.v)), Padding(padding: EdgeInsets.only(left: 5.h), child: Text("lbl_23_rating".tr, style: CustomTextStyles.bodyLargeAmberA400))])])), Spacer(), Padding(padding: EdgeInsets.only(top: 22.v, bottom: 23.v), child: CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(10.h), decoration: IconButtonStyleHelper.fillPrimaryTL25, child: CustomImageView(imagePath: ImageConstant.imgChat))), Padding(padding: EdgeInsets.only(left: 5.h, top: 22.v, bottom: 23.v), child: CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(10.h), decoration: IconButtonStyleHelper.fillAmberA, child: CustomImageView(imagePath: ImageConstant.imgPhone)))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
