import 'package:flutter/material.dart';import 'package:coffee_app/core/app_export.dart';import 'package:coffee_app/widgets/app_bar/appbar_leading_image.dart';import 'package:coffee_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:coffee_app/widgets/app_bar/custom_app_bar.dart';import 'package:coffee_app/widgets/custom_elevated_button.dart';import 'package:coffee_app/widgets/custom_radio_button.dart';import 'package:coffee_app/widgets/custom_text_form_field.dart';import '../top_up_action_screen/widgets/widget4_item_widget.dart';import 'controller/top_up_action_controller.dart';import 'models/widget4_item_model.dart';class TopUpActionScreen extends GetWidget<TopUpActionController> {const TopUpActionScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 17.v), child: Column(children: [SizedBox(height: 22.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_amount".tr, style: theme.textTheme.bodyLarge))), SizedBox(height: 9.v), _buildWidget(), SizedBox(height: 30.v), Padding(padding: EdgeInsets.only(left: 10.h), child: CustomTextFormField(controller: controller.uSDController, hintText: "lbl_72_00".tr, hintStyle: CustomTextStyles.headlineSmallBlack900_2, textInputAction: TextInputAction.done, suffix: Padding(padding: EdgeInsets.fromLTRB(10.h, 16.v, 19.h, 15.v), child: Text("lbl_usd".tr, style: TextStyle(color: Color(0XFF000000), fontSize: 25.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w500))), suffixConstraints: BoxConstraints(maxHeight: 70.v), contentPadding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 16.v), borderDecoration: TextFormFieldStyleHelper.fillBlackTL10, filled: true, fillColor: appTheme.black900.withOpacity(0.1))), SizedBox(height: 30.v), Divider(indent: 10.h, endIndent: 10.h), SizedBox(height: 21.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_select_payment".tr, style: CustomTextStyles.headlineSmallBlack900Medium))), SizedBox(height: 7.v), _buildSelectPayment(), Spacer(), Text("msg_agree_return_and".tr, style: CustomTextStyles.titleLargeIndigoA700)])), bottomNavigationBar: _buildTopUpNow())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 51.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 67.v, bottom: 19.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_top_up".tr, margin: EdgeInsets.only(top: 62.v, bottom: 7.v)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildWidget() { return Obx(() => Wrap(runSpacing: 10.v, spacing: 10.h, children: List<Widget>.generate(controller.topUpActionModelObj.value.widget4ItemList.value.length, (index) {Widget4ItemModel model = controller.topUpActionModelObj.value.widget4ItemList.value[index]; return Widget4ItemWidget(model);}))); } 
/// Section Widget
Widget _buildSelectPayment() { return Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: Obx(() => Column(children: [CustomRadioButton(text: "lbl_aba_bank".tr, value: controller.topUpActionModelObj.value.radioList.value[0], groupValue: controller.selectPayment.value, padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 10.v), decoration: RadioStyleHelper.fillAmberA, onChange: (value) {controller.selectPayment.value = value;}), Padding(padding: EdgeInsets.only(top: 10.v), child: CustomRadioButton(text: "lbl_wing_bank".tr, value: controller.topUpActionModelObj.value.radioList.value[1], groupValue: controller.selectPayment.value, padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 10.v), onChange: (value) {controller.selectPayment.value = value;})), Padding(padding: EdgeInsets.only(top: 10.v), child: CustomRadioButton(text: "lbl_acleda_bank".tr, value: controller.topUpActionModelObj.value.radioList.value[2], groupValue: controller.selectPayment.value, padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 10.v), onChange: (value) {controller.selectPayment.value = value;}))]))); } 
/// Section Widget
Widget _buildTopUpNow() { return CustomElevatedButton(text: "lbl_top_up_now".tr, margin: EdgeInsets.only(left: 24.h, right: 23.h, bottom: 34.v)); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
