import 'package:flutter/material.dart';import 'package:coffee_app/core/app_export.dart';import 'package:coffee_app/widgets/app_bar/appbar_leading_image.dart';import 'package:coffee_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:coffee_app/widgets/app_bar/custom_app_bar.dart';import 'package:coffee_app/widgets/custom_elevated_button.dart';import 'package:coffee_app/widgets/custom_rating_bar.dart';import 'controller/request_refund_action_controller.dart';import 'models/requestrefundaction_item_model.dart';import 'widgets/requestrefundaction_item_widget.dart';class RequestRefundActionScreen extends GetWidget<RequestRefundActionController> {const RequestRefundActionScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildFavorite(), SizedBox(height: 20.v), Text("lbl_your_reason".tr, style: CustomTextStyles.headlineSmallBlack900_2), SizedBox(height: 9.v), _buildRectangle(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildContinue())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 51.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 67.v, bottom: 19.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_request_refund".tr, margin: EdgeInsets.only(top: 61.v, bottom: 8.v)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildFavorite() { return Container(margin: EdgeInsets.only(right: 10.h), padding: EdgeInsets.symmetric(vertical: 14.v), decoration: AppDecoration.fillBlack9002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [SizedBox(height: 150.v, width: 165.h, child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgRectangle190, height: 150.v, width: 165.h, radius: BorderRadius.circular(20.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgFavoriteOnprimary, height: 16.v, width: 18.h, alignment: Alignment.topRight, margin: EdgeInsets.only(top: 14.v, right: 30.h))])), Padding(padding: EdgeInsets.only(top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text("lbl_mocha_frappe".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 2.v), Padding(padding: EdgeInsets.only(left: 51.h), child: Text("lbl_price".tr, style: theme.textTheme.bodyLarge)), SizedBox(width: 155.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_2_50".tr, style: CustomTextStyles.headlineSmallBlack900Regular.copyWith(decoration: TextDecoration.lineThrough)), Text("lbl_1_50".tr, style: CustomTextStyles.headlineSmallBlack900Regular)])), SizedBox(height: 9.v), CustomRatingBar(alignment: Alignment.center, initialRating: 3, itemSize: 18), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 37.h), child: Text("lbl_212_rating".tr, style: CustomTextStyles.bodyLargeAmberA400))]))])); } 
/// Section Widget
Widget _buildRectangle() { return Container(decoration: AppDecoration.fillBlack9002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 17.v), Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Obx(() => GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 131.v, crossAxisCount: 2, mainAxisSpacing: 7.h, crossAxisSpacing: 7.h), physics: NeverScrollableScrollPhysics(), itemCount: controller.requestRefundActionModelObj.value.requestrefundactionItemList.value.length, itemBuilder: (context, index) {RequestrefundactionItemModel model = controller.requestRefundActionModelObj.value.requestrefundactionItemList.value[index]; return RequestrefundactionItemWidget(model);}))), SizedBox(height: 28.v), Container(padding: EdgeInsets.symmetric(horizontal: 28.h, vertical: 19.v), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgEllipse32, height: 60.adaptSize, width: 60.adaptSize, radius: BorderRadius.circular(30.h), margin: EdgeInsets.only(bottom: 7.v)), Padding(padding: EdgeInsets.only(left: 20.h, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_tommi".tr, style: theme.textTheme.titleLarge), Text("msg_service_is_so_bad".tr, style: theme.textTheme.titleLarge)]))]))])); } 
/// Section Widget
Widget _buildContinue() { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 24.h, right: 23.h, bottom: 34.v)); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
