import 'package:flutter/material.dart';import 'package:coffee_app/core/app_export.dart';import 'package:coffee_app/widgets/app_bar/appbar_leading_image.dart';import 'package:coffee_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:coffee_app/widgets/app_bar/custom_app_bar.dart';import 'package:coffee_app/widgets/custom_elevated_button.dart';import 'package:coffee_app/widgets/custom_outlined_button.dart';import 'controller/gift_card_controller.dart';class GiftCardScreen extends GetWidget<GiftCardController> {const GiftCardScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 34.v), child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [Spacer(), CustomOutlinedButton(text: "lbl_add_gift_card".tr), SizedBox(height: 10.v), CustomElevatedButton(text: "lbl_buy_gift_card".tr)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 51.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 67.v, bottom: 19.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_gift_card".tr, margin: EdgeInsets.only(top: 58.v, bottom: 11.v)), actions: [Padding(padding: EdgeInsets.fromLTRB(24.h, 66.v, 24.h, 21.v), child: Column(children: [Row(children: [Container(height: 5.adaptSize, width: 5.adaptSize, decoration: BoxDecoration(color: theme.colorScheme.onPrimary.withOpacity(1), borderRadius: BorderRadius.circular(2.h))), Container(height: 5.v, width: 15.h, margin: EdgeInsets.only(left: 3.h), decoration: BoxDecoration(color: theme.colorScheme.onPrimary.withOpacity(1), borderRadius: BorderRadius.circular(2.h)))]), SizedBox(height: 3.v), Padding(padding: EdgeInsets.only(right: 5.h), child: Row(children: [Container(height: 5.adaptSize, width: 5.adaptSize, decoration: BoxDecoration(color: theme.colorScheme.onPrimary.withOpacity(1), borderRadius: BorderRadius.circular(2.h))), Container(height: 5.v, width: 10.h, margin: EdgeInsets.only(left: 3.h), decoration: BoxDecoration(color: theme.colorScheme.onPrimary.withOpacity(1), borderRadius: BorderRadius.circular(2.h)))])), SizedBox(height: 3.v), Row(children: [Container(height: 5.adaptSize, width: 5.adaptSize, decoration: BoxDecoration(color: theme.colorScheme.onPrimary.withOpacity(1), borderRadius: BorderRadius.circular(2.h))), Container(height: 5.v, width: 15.h, margin: EdgeInsets.only(left: 3.h), decoration: BoxDecoration(color: theme.colorScheme.onPrimary.withOpacity(1), borderRadius: BorderRadius.circular(2.h)))])]))], styleType: Style.bgShadow); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
