import 'package:flutter/material.dart';import 'package:coffee_app/core/app_export.dart';import 'package:coffee_app/widgets/app_bar/appbar_leading_image.dart';import 'package:coffee_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:coffee_app/widgets/app_bar/custom_app_bar.dart';import 'package:coffee_app/widgets/custom_elevated_button.dart';import 'package:coffee_app/widgets/custom_text_form_field.dart';import 'controller/write_review_one_controller.dart';class WriteReviewOneScreen extends GetWidget<WriteReviewOneController> {const WriteReviewOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v), child: Column(children: [_buildAmakadoHot(), SizedBox(height: 22.v), Text("lbl_ratings".tr, style: CustomTextStyles.titleLargeMedium), SizedBox(height: 17.v), _buildSignal(), SizedBox(height: 6.v), Text("msg_rate_your_coffee".tr, style: CustomTextStyles.bodyLargeBlack900_3), SizedBox(height: 17.v), Text("lbl_take_photo".tr, style: CustomTextStyles.titleLargeMedium), SizedBox(height: 20.v), _buildCamera(), SizedBox(height: 20.v), Text("lbl_your_comment".tr, style: CustomTextStyles.titleLargeMedium), SizedBox(height: 19.v), CustomTextFormField(controller: controller.group122Controller, hintText: "msg_write_your_experience".tr, hintStyle: theme.textTheme.titleLarge!, textInputAction: TextInputAction.done, maxLines: 3, contentPadding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 21.v))])), bottomNavigationBar: _buildPost())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 51.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 67.v, bottom: 19.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_new_review".tr, margin: EdgeInsets.only(top: 58.v, bottom: 11.v)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildAmakadoHot() { return Container(padding: EdgeInsets.all(20.h), decoration: AppDecoration.fillBlack9002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(children: [Container(height: 120.adaptSize, width: 120.adaptSize, decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: CustomImageView(imagePath: ImageConstant.imgImage28120x120, height: 120.adaptSize, width: 120.adaptSize, radius: BorderRadius.circular(10.h), alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 20.h, top: 10.v, bottom: 6.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_amakado_hot".tr, style: CustomTextStyles.titleLargeSemiBold), SizedBox(height: 5.v), Text("lbl_price".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 5.v), SizedBox(width: 160.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_5_50".tr, style: CustomTextStyles.headlineSmallBlack900Regular.copyWith(decoration: TextDecoration.lineThrough)), Text("lbl_3_50".tr, style: CustomTextStyles.headlineSmallBlack900Regular)]))]))])); } 
/// Section Widget
Widget _buildSignal() { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), padding: EdgeInsets.symmetric(horizontal: 34.h, vertical: 22.v), decoration: AppDecoration.fillBlack9002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomImageView(imagePath: ImageConstant.imgSignalBlack900, height: 36.v, width: 40.h, margin: EdgeInsets.only(right: 10.h))), Expanded(child: CustomImageView(imagePath: ImageConstant.imgSignalBlack900, height: 36.v, width: 40.h, margin: EdgeInsets.symmetric(horizontal: 10.h))), Expanded(child: CustomImageView(imagePath: ImageConstant.imgSignalBlack900, height: 36.v, width: 40.h, margin: EdgeInsets.symmetric(horizontal: 10.h))), Expanded(child: CustomImageView(imagePath: ImageConstant.imgSignalBlack900, height: 36.v, width: 40.h, margin: EdgeInsets.symmetric(horizontal: 10.h))), Expanded(child: CustomImageView(imagePath: ImageConstant.imgSignalBlack900, height: 36.v, width: 40.h, margin: EdgeInsets.only(left: 10.h)))])); } 
/// Section Widget
Widget _buildCamera() { return Container(padding: EdgeInsets.symmetric(horizontal: 159.h, vertical: 20.v), decoration: AppDecoration.fillBlack9002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: CustomImageView(imagePath: ImageConstant.imgCamera, height: 60.adaptSize, width: 60.adaptSize)); } 
/// Section Widget
Widget _buildPost() { return CustomElevatedButton(text: "lbl_post".tr, margin: EdgeInsets.only(left: 24.h, right: 23.h, bottom: 34.v)); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
