import 'package:flutter/material.dart';import 'package:coffee_app/core/app_export.dart';import 'package:coffee_app/widgets/app_bar/appbar_leading_image.dart';import 'package:coffee_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:coffee_app/widgets/app_bar/custom_app_bar.dart';import 'package:coffee_app/widgets/custom_icon_button.dart';import 'controller/about_controller.dart';class AboutScreen extends GetWidget<AboutController> {const AboutScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 22.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomIconButton(height: 45.adaptSize, width: 45.adaptSize, padding: EdgeInsets.all(8.h), child: CustomImageView(imagePath: ImageConstant.imgInbox)), Padding(padding: EdgeInsets.only(left: 15.h, top: 8.v, bottom: 6.v), child: Text("msg_policy_and_privacy".tr, style: CustomTextStyles.titleLargeMedium))]), SizedBox(height: 12.v), Divider(), SizedBox(height: 12.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomIconButton(height: 45.adaptSize, width: 45.adaptSize, padding: EdgeInsets.all(8.h), child: CustomImageView(imagePath: ImageConstant.imgInbox)), Padding(padding: EdgeInsets.only(left: 15.h, top: 6.v, bottom: 8.v), child: Text("lbl_term_of_service".tr, style: CustomTextStyles.titleLargeMedium))]), SizedBox(height: 12.v), Divider(), SizedBox(height: 12.v), Row(children: [CustomIconButton(height: 45.adaptSize, width: 45.adaptSize, padding: EdgeInsets.all(8.h), child: CustomImageView(imagePath: ImageConstant.imgInbox)), Padding(padding: EdgeInsets.only(left: 15.h, top: 9.v, bottom: 5.v), child: Text("lbl_about_company".tr, style: CustomTextStyles.titleLargeMedium))]), SizedBox(height: 12.v), Divider(), SizedBox(height: 12.v), Row(children: [CustomIconButton(height: 45.adaptSize, width: 45.adaptSize, padding: EdgeInsets.all(11.h), child: CustomImageView(imagePath: ImageConstant.imgProfile)), Padding(padding: EdgeInsets.only(left: 15.h, top: 8.v, bottom: 6.v), child: Text("lbl_faqs".tr, style: CustomTextStyles.titleLargeMedium))]), SizedBox(height: 12.v), Divider(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildChat())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 51.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 67.v, bottom: 19.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_about_us".tr, margin: EdgeInsets.only(top: 58.v, bottom: 11.v)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildChat() { return Container(margin: EdgeInsets.only(left: 54.h, right: 43.h, bottom: 59.v), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [Expanded(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 50.adaptSize, width: 50.adaptSize, margin: EdgeInsets.symmetric(vertical: 8.v), decoration: AppDecoration.pink.copyWith(borderRadius: BorderRadiusStyle.circleBorder40), child: CustomImageView(imagePath: ImageConstant.imgChat, height: 50.adaptSize, width: 50.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 30.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_live_chat".tr, style: CustomTextStyles.titleLargeSemiBold), Padding(padding: EdgeInsets.only(top: 12.v), child: Text("msg_we_are_ready_to".tr, style: theme.textTheme.bodyLarge))]))])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 25.v, width: 12.h, margin: EdgeInsets.only(left: 44.h, top: 19.v, bottom: 22.v))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
