import 'package:flutter/material.dart';import 'package:coffee_app/core/app_export.dart';import 'package:coffee_app/widgets/app_bar/appbar_leading_image.dart';import 'package:coffee_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:coffee_app/widgets/app_bar/custom_app_bar.dart';import 'package:coffee_app/widgets/custom_elevated_button.dart';import 'package:coffee_app/widgets/custom_rating_bar.dart';import 'package:coffee_app/widgets/custom_text_form_field.dart';import 'controller/request_refund_controller.dart';class RequestRefundScreen extends GetWidget<RequestRefundController> {const RequestRefundScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [_buildFavorite(), SizedBox(height: 20.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_your_reason".tr, style: CustomTextStyles.headlineSmallBlack900_2)), SizedBox(height: 9.v), _buildCamera(), SizedBox(height: 20.v), Text("lbl_your_comment".tr, style: CustomTextStyles.titleLargeMedium), SizedBox(height: 19.v), CustomTextFormField(controller: controller.group329Controller, hintText: "msg_write_your_experience".tr, hintStyle: theme.textTheme.titleLarge!, textInputAction: TextInputAction.done, maxLines: 3, contentPadding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 21.v)), SizedBox(height: 3.v)])), bottomNavigationBar: _buildContinue())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 51.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 67.v, bottom: 19.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_request_refund".tr, margin: EdgeInsets.only(top: 61.v, bottom: 8.v)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildFavorite() { return Container(margin: EdgeInsets.only(right: 10.h), padding: EdgeInsets.symmetric(vertical: 14.v), decoration: AppDecoration.fillBlack9002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [SizedBox(height: 150.v, width: 165.h, child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgRectangle190, height: 150.v, width: 165.h, radius: BorderRadius.circular(20.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgFavoriteOnprimary, height: 16.v, width: 18.h, alignment: Alignment.topRight, margin: EdgeInsets.only(top: 14.v, right: 30.h))])), Padding(padding: EdgeInsets.only(top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text("lbl_mocha_frappe".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 2.v), Padding(padding: EdgeInsets.only(left: 51.h), child: Text("lbl_price".tr, style: theme.textTheme.bodyLarge)), SizedBox(width: 155.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_2_50".tr, style: CustomTextStyles.headlineSmallBlack900Regular.copyWith(decoration: TextDecoration.lineThrough)), Text("lbl_1_50".tr, style: CustomTextStyles.headlineSmallBlack900Regular)])), SizedBox(height: 9.v), CustomRatingBar(alignment: Alignment.center, initialRating: 3, itemSize: 18), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 37.h), child: Text("lbl_212_rating".tr, style: CustomTextStyles.bodyLargeAmberA400))]))])); } 
/// Section Widget
Widget _buildCamera() { return Container(padding: EdgeInsets.symmetric(horizontal: 130.h, vertical: 77.v), decoration: AppDecoration.fillBlack9002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), CustomImageView(imagePath: ImageConstant.imgCamera60x60, height: 60.adaptSize, width: 60.adaptSize), SizedBox(height: 1.v), SizedBox(width: 120.h, child: Text("msg_take_3_or_6_picture_to".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumBlack900_1))])); } 
/// Section Widget
Widget _buildContinue() { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 24.h, right: 23.h, bottom: 34.v)); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
