import 'package:flutter/material.dart';import 'package:coffee_app/core/app_export.dart';import 'package:coffee_app/widgets/app_bar/appbar_leading_image.dart';import 'package:coffee_app/widgets/app_bar/custom_app_bar.dart';import 'controller/get_help_controller.dart';class GetHelpScreen extends GetWidget<GetHelpController> {const GetHelpScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 11.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgGroup, height: 159.adaptSize, width: 159.adaptSize, alignment: Alignment.center), SizedBox(height: 30.v), Align(alignment: Alignment.center, child: Text("lbl_get_help".tr, style: theme.textTheme.displaySmall)), SizedBox(height: 6.v), Align(alignment: Alignment.center, child: Container(width: 336.h, margin: EdgeInsets.symmetric(horizontal: 31.h), child: Text("msg_we_are_here_to_help".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleLargeAmberA400))), SizedBox(height: 28.v), Padding(padding: EdgeInsets.only(left: 9.h), child: Row(children: [Container(height: 70.adaptSize, width: 70.adaptSize, padding: EdgeInsets.all(12.h), decoration: AppDecoration.fillBlack9001.copyWith(borderRadius: BorderRadiusStyle.circleBorder35), child: CustomImageView(imagePath: ImageConstant.imgPhone, height: 45.adaptSize, width: 45.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 19.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_hotline".tr, style: CustomTextStyles.titleLargeMedium), SizedBox(height: 10.v), Text("lbl_1_234_566_789".tr, style: theme.textTheme.titleLarge)]))])), SizedBox(height: 18.v), Divider(color: appTheme.black900.withOpacity(0.25), indent: 8.h, endIndent: 10.h), SizedBox(height: 10.v), Padding(padding: EdgeInsets.only(left: 9.h, right: 106.h), child: Row(children: [Container(height: 70.adaptSize, width: 70.adaptSize, margin: EdgeInsets.only(bottom: 1.v), padding: EdgeInsets.all(12.h), decoration: AppDecoration.fillBlack9001.copyWith(borderRadius: BorderRadiusStyle.circleBorder35), child: CustomImageView(imagePath: ImageConstant.imgAtSign45x45, height: 45.adaptSize, width: 45.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_email".tr, style: CustomTextStyles.titleLargeMedium), SizedBox(height: 12.v), Text("msg_support_cafe_com".tr, style: theme.textTheme.titleLarge)]))])), SizedBox(height: 16.v), Divider(color: appTheme.black900.withOpacity(0.25), endIndent: 18.h), SizedBox(height: 5.v)])), bottomNavigationBar: _buildChat())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 56.v, leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.fromLTRB(24.h, 16.v, 377.h, 17.v), onTap: () {onTapArrowLeft();})); } 
/// Section Widget
Widget _buildChat() { return Container(margin: EdgeInsets.only(left: 54.h, right: 43.h, bottom: 59.v), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [Expanded(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 50.adaptSize, width: 50.adaptSize, margin: EdgeInsets.symmetric(vertical: 8.v), decoration: AppDecoration.pink.copyWith(borderRadius: BorderRadiusStyle.circleBorder40), child: CustomImageView(imagePath: ImageConstant.imgChat, height: 50.adaptSize, width: 50.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 30.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_live_chat".tr, style: CustomTextStyles.titleLargeSemiBold), Padding(padding: EdgeInsets.only(top: 12.v), child: Text("msg_we_are_ready_to".tr, style: theme.textTheme.bodyLarge))]))])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 25.v, width: 12.h, margin: EdgeInsets.only(left: 44.h, top: 19.v, bottom: 22.v))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
