import '../../../core/app_export.dart';import 'userprofile9_item_model.dart';import 'userprofile10_item_model.dart';import 'hotexpresso_item_model.dart';/// This class defines the variables used in the [cafe_following_page],
/// and is typically used to hold data that is passed between different parts of the application.
class CafeFollowingModel {Rx<List<Userprofile9ItemModel>> userprofile9ItemList = Rx([Userprofile9ItemModel(circleImage:ImageConstant.imgImage1685x85.obs,textStarbucks: "Starbucks".obs,imageRating:ImageConstant.imgSignal.obs,textRating: "8.1 Rating".obs,follow: "Follow".obs,textFollowers: "10K".obs),Userprofile9ItemModel(circleImage:ImageConstant.imgEllipse2085x85.obs,textStarbucks: "Amazon".obs,follow: "Follow".obs,textFollowers: "10K".obs),Userprofile9ItemModel(circleImage:ImageConstant.imgEllipse202.obs,textStarbucks: "Luna".obs,follow: "Follow".obs,textFollowers: "92K".obs),Userprofile9ItemModel(circleImage:ImageConstant.imgEllipse203.obs,textStarbucks: "Brown".obs,follow: "Follow".obs,textFollowers: "10K".obs)]);

Rx<List<Userprofile10ItemModel>> userprofile10ItemList = Rx([Userprofile10ItemModel(userImage:ImageConstant.imgEllipse2040x40.obs,userName: "Luna".obs),Userprofile10ItemModel(userImage:ImageConstant.imgEllipse206.obs,userName: "Ama".obs),Userprofile10ItemModel(userImage:ImageConstant.imgImage1640x40.obs,userName: "Luna".obs)]);

Rx<List<HotexpressoItemModel>> hotexpressoItemList = Rx([HotexpressoItemModel(hotExpresso:ImageConstant.imgImage27.obs,favorite:ImageConstant.imgFavoriteOnprimary.obs,hotExpresso1: "Hot Expresso".obs,price: "Price".obs,price1: "3.20".obs,price2: "2.20".obs,ratingCounter: "92 rating".obs),HotexpressoItemModel(hotExpresso:ImageConstant.imgImage28.obs,favorite:ImageConstant.imgFavorite.obs,hotExpresso1: "Amakado Hot".obs,price: "Price".obs,price1: "3.50".obs,price2: "2.50".obs,ratingCounter: "34 rating".obs),HotexpressoItemModel(hotExpresso:ImageConstant.imgImage20.obs,favorite:ImageConstant.imgFavorite.obs,hotExpresso1: "Mocha Frappe".obs,price: "Price".obs,price1: "5.50".obs,price2: "3.50".obs,ratingCounter: "152 rating".obs),HotexpressoItemModel(hotExpresso:ImageConstant.imgImage26.obs,favorite:ImageConstant.imgFavoriteOnprimary.obs,hotExpresso1: "Ice Green Tea".obs,price: "Price".obs,price1: "2.50".obs,price2: "1.50".obs,ratingCounter: "302 rating".obs),HotexpressoItemModel(hotExpresso:ImageConstant.imgImage27.obs,favorite:ImageConstant.imgFavoriteOnprimary.obs,hotExpresso1: "Hot Expresso".obs,price: "Price".obs,price1: "3.20".obs,price2: "2.20".obs,ratingCounter: "92 rating".obs),HotexpressoItemModel(hotExpresso:ImageConstant.imgImage28.obs,favorite:ImageConstant.imgFavorite.obs,hotExpresso1: "Amakado Hot".obs,price: "Price".obs,price1: "3.50".obs,price2: "2.50".obs,ratingCounter: "34 rating".obs)]);

 }
