import 'package:flutter/material.dart';import 'package:coffee_app/core/app_export.dart';import 'package:coffee_app/widgets/app_bar/appbar_leading_image.dart';import 'package:coffee_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:coffee_app/widgets/app_bar/custom_app_bar.dart';import 'package:coffee_app/widgets/custom_elevated_button.dart';import 'controller/waiting_controller.dart';class WaitingScreen extends GetWidget<WaitingController> {const WaitingScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 43.h), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 11.v), CustomImageView(imagePath: ImageConstant.imgImage54, height: 170.adaptSize, width: 170.adaptSize), SizedBox(height: 33.v), Text("msg_wait_your_pickup".tr, style: CustomTextStyles.displaySmallPrimary), SizedBox(height: 26.v), CustomElevatedButton(height: 100.v, text: "lbl_done".tr, margin: EdgeInsets.symmetric(horizontal: 21.h), buttonStyle: CustomButtonStyles.fillAmberATL50, buttonTextStyle: theme.textTheme.displaySmall!), SizedBox(height: 21.v), Text("msg_process_done_wait".tr, style: theme.textTheme.bodyLarge)])), bottomNavigationBar: _buildSeventeen())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 51.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 67.v, bottom: 19.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_waiting".tr, margin: EdgeInsets.only(top: 61.v, bottom: 8.v)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildSeventeen() { return Container(margin: EdgeInsets.only(left: 54.h, right: 43.h, bottom: 59.v), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [Expanded(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 50.adaptSize, width: 50.adaptSize, margin: EdgeInsets.symmetric(vertical: 8.v), decoration: AppDecoration.pink.copyWith(borderRadius: BorderRadiusStyle.circleBorder40), child: CustomImageView(imagePath: ImageConstant.imgChat, height: 50.adaptSize, width: 50.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 30.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_live_chat".tr, style: CustomTextStyles.titleLargeSemiBold), Padding(padding: EdgeInsets.only(top: 12.v), child: Text("msg_we_are_ready_to".tr, style: theme.textTheme.bodyLarge))]))])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 25.v, width: 12.h, margin: EdgeInsets.only(left: 44.h, top: 19.v, bottom: 22.v))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
