import 'package:flutter/material.dart';import 'package:coffee_app/core/app_export.dart';import 'package:coffee_app/presentation/cafe_following_page/cafe_following_page.dart';import 'package:coffee_app/widgets/app_bar/appbar_leading_image.dart';import 'package:coffee_app/widgets/app_bar/appbar_title_edittext_one.dart';import 'package:coffee_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:coffee_app/widgets/app_bar/custom_app_bar.dart';import 'package:coffee_app/widgets/custom_bottom_bar.dart';import 'package:coffee_app/widgets/custom_elevated_button.dart';import 'controller/search_shop_action_controller.dart';class SearchShopActionScreen extends GetWidget<SearchShopActionController> {const SearchShopActionScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Padding(padding: EdgeInsets.only(top: 7.v, bottom: 2.v), child: Text("lbl_shop".tr, style: CustomTextStyles.titleLargeBlack900SemiBold)), CustomElevatedButton(height: 40.v, width: 160.h, text: "lbl_search_shop".tr, margin: EdgeInsets.only(left: 20.h), buttonStyle: CustomButtonStyles.fillPrimaryTL20, buttonTextStyle: CustomTextStyles.titleLargeOnPrimarySemiBold)]), SizedBox(height: 30.v), _buildWidget(), SizedBox(height: 10.v), _buildBrown(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 112.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 25.h, top: 66.v, bottom: 24.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarTitleEdittextOne(margin: EdgeInsets.only(top: 54.v, bottom: 13.v), hintText: "lbl_brown_coffee".tr, controller: controller.coffeeController), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgSend, margin: EdgeInsets.fromLTRB(24.h, 67.v, 24.h, 22.v))], styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildWidget() { return SizedBox(height: 200.v, width: 380.h, child: Stack(alignment: Alignment.centerLeft, children: [CustomImageView(imagePath: ImageConstant.imgRectangle194, height: 200.v, width: 380.h, radius: BorderRadius.circular(20.h), alignment: Alignment.center), Align(alignment: Alignment.centerLeft, child: Container(height: 100.adaptSize, width: 100.adaptSize, margin: EdgeInsets.only(left: 29.h), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.circleBorder50), child: CustomImageView(imagePath: ImageConstant.imgEllipse20100x100, height: 100.adaptSize, width: 100.adaptSize, radius: BorderRadius.circular(50.h), alignment: Alignment.center)))])); } 
/// Section Widget
Widget _buildBrown() { return Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_brown".tr, style: CustomTextStyles.headlineSmallBlack900_2), SizedBox(height: 1.v), Text("msg_free_delivery".tr, style: theme.textTheme.bodyLarge)]), Spacer(), CustomImageView(imagePath: ImageConstant.imgSignal, height: 18.v, width: 19.h, margin: EdgeInsets.only(top: 12.v, bottom: 32.v)), Padding(padding: EdgeInsets.only(left: 10.h, top: 9.v, bottom: 23.v), child: Text("lbl_8_1_rating".tr, style: CustomTextStyles.titleLargeAmberA400))]); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.cafeFollowingPage; case BottomBarEnum.Orders: return "/"; case BottomBarEnum.Chat: return "/"; case BottomBarEnum.Cart: return "/"; case BottomBarEnum.Profile: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.cafeFollowingPage: return CafeFollowingPage(); default: return DefaultWidget();} } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
