import 'package:flutter/material.dart';import 'package:coffee_app/core/app_export.dart';import 'package:coffee_app/widgets/app_bar/appbar_leading_image.dart';import 'package:coffee_app/widgets/app_bar/custom_app_bar.dart';import 'package:coffee_app/widgets/custom_elevated_button.dart';import 'package:coffee_app/widgets/custom_pin_code_text_field.dart';import 'controller/verify_controller.dart';class VerifyScreen extends GetWidget<VerifyController> {const VerifyScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 11.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgMaskGroup, height: 164.adaptSize, width: 164.adaptSize), SizedBox(height: 24.v), Text("lbl_verify_otp".tr, style: theme.textTheme.displaySmall), SizedBox(height: 8.v), Text("msg_check_otp_code_in".tr, style: CustomTextStyles.titleLargeAmberA400), SizedBox(height: 33.v), Obx(() => CustomPinCodeTextField(context: Get.context!, controller: controller.otpController.value, onChanged: (value) {})), SizedBox(height: 22.v), RichText(text: TextSpan(children: [TextSpan(text: "msg_don_t_receive_code3".tr, style: CustomTextStyles.bodyLargebf000000), TextSpan(text: "lbl_sent_again".tr, style: CustomTextStyles.bodyLargeff2454f8)]), textAlign: TextAlign.left), SizedBox(height: 27.v), CustomElevatedButton(text: "lbl_verify".tr), Spacer(), SizedBox(height: 12.v), RichText(text: TextSpan(children: [TextSpan(text: "msg_your_have_any_problem2".tr, style: CustomTextStyles.titleLarge7f000000), TextSpan(text: " "), TextSpan(text: "lbl_help".tr, style: CustomTextStyles.titleLargeff2454f8)]), textAlign: TextAlign.left)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 106.v, leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.fromLTRB(25.h, 16.v, 376.h, 17.v), onTap: () {onTapArrowLeft();})); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
