import 'package:flutter/material.dart';import 'package:coffee_app/core/app_export.dart';import 'package:coffee_app/widgets/app_bar/appbar_leading_image.dart';import 'package:coffee_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:coffee_app/widgets/app_bar/custom_app_bar.dart';import 'package:coffee_app/widgets/custom_elevated_button.dart';import 'controller/address_controller.dart';class AddressScreen extends GetWidget<AddressController> {const AddressScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(height: 818.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgScreenshot20221008, height: 823.v, width: 428.h, alignment: Alignment.center), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(left: 23.h, right: 23.h, bottom: 34.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 157.v, width: 140.h, margin: EdgeInsets.only(left: 100.h), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.bottomCenter, child: Container(height: 140.adaptSize, width: 140.adaptSize, decoration: BoxDecoration(color: appTheme.black900.withOpacity(0.1), borderRadius: BorderRadius.circular(70.h)))), CustomImageView(imagePath: ImageConstant.imgImage42, height: 100.adaptSize, width: 100.adaptSize, alignment: Alignment.topCenter)])), SizedBox(height: 118.v), _buildLocation(), SizedBox(height: 10.v), CustomElevatedButton(text: "msg_add_new_location".tr)])))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 51.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 67.v, bottom: 19.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_address".tr, margin: EdgeInsets.only(top: 58.v, bottom: 11.v)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildLocation() { return Container(width: 381.h, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 13.v), decoration: AppDecoration.outlineBlack9003.copyWith(borderRadius: BorderRadiusStyle.circleBorder29), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("lbl_location".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 6.v), Container(width: 260.h, margin: EdgeInsets.only(right: 80.h), child: Text("msg_st_272_terk_thlar".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleLargeMedium))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
