import 'package:flutter/material.dart';import 'package:coffee_app/core/app_export.dart';import 'package:coffee_app/widgets/app_bar/appbar_leading_image.dart';import 'package:coffee_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:coffee_app/widgets/app_bar/custom_app_bar.dart';import 'package:coffee_app/widgets/custom_elevated_button.dart';import 'package:coffee_app/widgets/custom_outlined_button.dart';import 'controller/refund_status_controller.dart';class RefundStatusScreen extends GetWidget<RefundStatusController> {const RefundStatusScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 20.v), child: Column(children: [_buildDuration(), SizedBox(height: 30.v), Divider(), SizedBox(height: 29.v), _buildRefresh(), SizedBox(height: 30.v), Divider(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildGetHelp())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 51.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 67.v, bottom: 19.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_refund_status".tr, margin: EdgeInsets.only(top: 58.v, bottom: 11.v)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildDuration() { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 26.h, vertical: 10.v), decoration: AppDecoration.fillBlack9002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgEllipse73, height: 60.adaptSize, width: 60.adaptSize, radius: BorderRadius.circular(30.h)), Padding(padding: EdgeInsets.only(left: 20.h, top: 14.v, bottom: 15.v), child: Text("msg_it_s_take_24hour".tr, style: theme.textTheme.titleLarge))])); } 
/// Section Widget
Widget _buildRefresh() { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 110.h, vertical: 65.v), decoration: AppDecoration.fillBlack9002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse74, height: 160.adaptSize, width: 160.adaptSize, radius: BorderRadius.circular(80.h)), SizedBox(height: 12.v), Text("lbl_padding".tr, style: CustomTextStyles.titleLargeMedium), SizedBox(height: 7.v), CustomElevatedButton(height: 40.v, text: "lbl_refresh".tr, margin: EdgeInsets.only(left: 13.h, right: 7.h), buttonStyle: CustomButtonStyles.fillAmberATL10, buttonTextStyle: CustomTextStyles.titleMediumOnPrimaryMedium)])); } 
/// Section Widget
Widget _buildGetHelp() { return CustomOutlinedButton(height: 90.v, width: 250.h, text: "lbl_get_help2".tr, margin: EdgeInsets.only(left: 89.h, right: 89.h, bottom: 40.v), buttonStyle: CustomButtonStyles.outlinePrimaryTL45, buttonTextStyle: CustomTextStyles.headlineSmallPrimary_1); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
