import 'package:flutter/material.dart';import 'package:coffee_app/core/app_export.dart';import 'package:coffee_app/widgets/app_bar/appbar_leading_image.dart';import 'package:coffee_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:coffee_app/widgets/app_bar/custom_app_bar.dart';import 'package:coffee_app/widgets/custom_icon_button.dart';import 'controller/call_controller.dart';class CallScreen extends GetWidget<CallController> {const CallScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.only(top: 116.v), child: Column(children: [Container(height: 200.adaptSize, width: 200.adaptSize, decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.circleBorder100), child: CustomImageView(imagePath: ImageConstant.imgImage16200x200, height: 200.adaptSize, width: 200.adaptSize, radius: BorderRadius.circular(100.h), alignment: Alignment.center)), SizedBox(height: 9.v), Text("lbl_starbucks".tr, style: theme.textTheme.displaySmall), SizedBox(height: 5.v), Text("lbl_00_15".tr, style: CustomTextStyles.headlineSmallBlack900Medium)])), bottomNavigationBar: _buildNinetyNine())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 122.v, leadingWidth: 51.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, top: 67.v, bottom: 33.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_calling".tr, margin: EdgeInsets.only(top: 61.v, bottom: 22.v)), styleType: Style.bgShadow_1); } 
/// Section Widget
Widget _buildNinetyNine() { return Container(margin: EdgeInsets.only(left: 69.h, right: 69.h, bottom: 39.v), decoration: AppDecoration.fillBlack9002.copyWith(borderRadius: BorderRadiusStyle.circleBorder29), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(top: 17.v, bottom: 18.v), child: CustomIconButton(height: 65.adaptSize, width: 65.adaptSize, padding: EdgeInsets.all(16.h), decoration: IconButtonStyleHelper.fillBlackTL32, child: CustomImageView(imagePath: ImageConstant.imgUserOnprimary))), Padding(padding: EdgeInsets.only(left: 30.h), child: CustomIconButton(height: 100.adaptSize, width: 100.adaptSize, padding: EdgeInsets.all(30.h), decoration: IconButtonStyleHelper.fillPrimary, child: CustomImageView(imagePath: ImageConstant.imgCall))), Padding(padding: EdgeInsets.only(left: 30.h, top: 17.v, bottom: 18.v), child: CustomIconButton(height: 65.adaptSize, width: 65.adaptSize, padding: EdgeInsets.all(15.h), decoration: IconButtonStyleHelper.fillBlackTL32, child: CustomImageView(imagePath: ImageConstant.imgGroup92)))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
